import { Track } from '@/hooks/useAudioPlayer';

// Free demo tracks from public domain (freemusicarchive / ccmixter via direct CDN links)
export const TRACKS: Track[] = [
  {
    id: 1,
    title: 'Neon Horizon',
    artist: 'SYNTHWAVE_X',
    genre: 'Electronic',
    duration: '2:30',
    bpm: 128,
    price: 990,
    tags: ['энергичный', 'футуристик'],
    src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  },
  {
    id: 2,
    title: 'Deep Forest',
    artist: 'AmbientLab',
    genre: 'Ambient',
    duration: '3:10',
    bpm: 75,
    price: 790,
    tags: ['спокойный', 'природа'],
    src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  },
  {
    id: 3,
    title: 'City Lights',
    artist: 'JazzFusion',
    genre: 'Jazz',
    duration: '3:42',
    bpm: 110,
    price: 1190,
    tags: ['ночной', 'атмосфера'],
    src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  },
  {
    id: 4,
    title: 'Epic Rising',
    artist: 'CINEMA_PRO',
    genre: 'Cinematic',
    duration: '2:58',
    bpm: 95,
    price: 1490,
    tags: ['эпик', 'динамика'],
    src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  },
  {
    id: 5,
    title: 'Lo-Fi Rain',
    artist: 'ChillBeats',
    genre: 'Hip-Hop',
    duration: '3:20',
    bpm: 85,
    price: 690,
    tags: ['расслабляющий', 'дождь'],
    src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
  },
  {
    id: 6,
    title: 'Morning Dew',
    artist: 'AcousticSoul',
    genre: 'Acoustic',
    duration: '4:33',
    bpm: 68,
    price: 890,
    tags: ['утро', 'живой'],
    src: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
  },
];
